version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf/task2.conf:/etc/nginx/conf.d/default.conf
      - ./www:/www
    networks:
      - task2
      - default
    ports:
      - 80:80
  php:
    build: ./php
    networks:
      - task2
    volumes:
    - ./www:/www
  redis:
    image: redis
    networks:
      - task2

networks:
  task2:
    ipam:
      config:
      - subnet: 172.31.201.0/24
    internal: true
  default:
    driver: bridge
